### PR TITLE
Docs: Refactor documentation

### LINKED ISSUE #709: Update Documentation for app Launch
- [ ] Update the Documentation to allow for analytics
- [ ] Update documentation design to use proper header and footer compatible with ODS

### PR DESCRIPTION
**Pull request by louismaximepiton**
### Description

⚠️ I haven't changed the GemFile.lock since I had trouble with it on Android side. Would be great if you can do it before merging 😄 

Certainly forgot to list some things in here but here are the main changes that this PR brings up.

* Refactoring of the main page, removing some CSS as well
* Adding the Orange font inside the doc
* Introducing some partials for header and footer for clearer template
* Added a page to explain the license and redirect to the license file directly
* Added a page to present the team maintaining the library
* Added an offcanvas wrapping the main navigation so it's usable from anywhere inside the page
* Added a default template that was missing for `404.html` page
* Added a title to each `*_docs.md` so it's now displayed as the title of the page
* Wrapped all markdown table with `<div class="table-responsive" markdown="1">...</div>` to make sure the mobile documentation is still readable at any time
* Tweaked a bit `/index*.md` to make sure the workaround inside the main navigation still works
* Added some comfort updates:
  * No need to update the table of content anymore, just add a section with `* Table of contents\n{:toc}` to have it rendered inside pages
  * No need to add the `{:.table}` before each table anymore (see `/_plugins/table-responsive.rb`). If the plugin is added to `/_plugins` it's auto imported inside the project (modulo dependencies)
  * Tables are now responsive by default with markdown template
* Update the `detail.html` to have the same rendering as the documentation
* Kept the CSS part as tidy as possible there are some `style` tags but I feel more comfy with this.
* Reorganized the main html part
* Set the main navigation in an offcanvas on mobile viewsize. It's toggled via the global header burger menu
* Updated the rendering of the global site to have a render closer to what Boosted propose.
* May need some updates while updating Boosted version
* Updated the main navigation to reflect which page is active
* Updated the `<header><main><footer>` places to have a better a11y base

### Related issues

Fixes #709.

### CODE REVIEW

**Comment by pylapp** [comment]
@louismaximepiton Could you rebase your branch from _qualif_ please? Your branch is out of date :)

**Comment by louismaximepiton** [comment]
Done, sorry for the delay 😕

**Comment by pylapp** [comment]
@louismaximepiton Still needed to rebase your branch ; since we igrated our runners our _qualif_ and yours are not aligned anymore. Contact me when you did the rebase so that we can merge your branch.

**Review by pylapp — APPROVED** [review]
LGTM

**Pull request merged**
